style: Format using ruff
canonical/lego-base-k8s-operator pull request #154
Opened 2024-07-16 17:29 UTC by DanielArndt

Currently, ruff is only configured to check the files for linting errors. This adds ruff formatting to tox checks.

Review notes:

Only tox.ini contains functional changes, the rest are the result of running tox -e format.

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I Have bumped the version of the library

2024-07-16 18:10 UTC, gruyaume requested changes

2024-07-16 18:10 UTC, gruyaume commented on lib/charms/lego_base_k8s/v0/lego_client.py
We forgot to bump the lib

2024-07-16 19:20 UTC, DanielArndt commented on lib/charms/lego_base_k8s/v0/lego_client.py
@gruyaume Do we really need to bump the lib if it's only style changes? I'm not sure if there's any value in releasing them with no other changes, but I can go through all bump all of them if you think it's worthwhile.

2024-07-17 11:26 UTC, DanielArndt commented on lib/charms/lego_base_k8s/v0/lego_client.py
In the end, there were less of these than I imagined across all the projects, so I'll bump them and save the discussion :laughing:

2024-07-17 12:37 UTC, gruyaume approved these changes

2024-07-17 12:52 UTC, merged